### ISSUE TITLE
How to delete a user?

### ISSUE THREAD

**Issue by vincentkedison** [Peppermint-Lab/peppermint#128] opened 2023-04-02 06:23 UTC
Hi. I recently review peppermint after watching networkchuck youtube.
However I cannot find the delete button for a user. Can someone help me?
Thanks

**Comment by ChaseCares** [comment] 2023-04-13 10:48
This should be coming in the next update

 duplicate of #102

**Comment by potts99** [comment] 2023-06-10 11:47
Thank you @ChaseCares -> This is now implemented

**Closed by potts99** 2023-06-10 11:47 UTC
