### ISSUE TITLE
Outbound email issue

### ISSUE THREAD

**Issue by BooluInji** [Peppermint-Lab/peppermint#215] opened 2024-01-06 23:53 UTC
We just got this set up locally and are using smtp.office365.com with a support email for outbound, however, we are not receiving any notifications. 

We made sure the account doesn't require MFA. We saw a sign-in log in Azure from the local server from Peppermint and it was successful, however, no email was generated.

I was checking to see if maybe we overlooked some things?

Best,

Jared

**Comment by rubenhoenle** [comment] 2024-01-22 17:45
Possible duplicate of https://github.com/Peppermint-Lab/peppermint/issues/207

**Closed** 2024-03-26 09:26 UTC
Labels: bug
